server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/customer
    username: amigoscode
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop # The schema will be destroyed at the end of the session
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect # Here we are using postgress dialect
        format_sql: true
      show-sql: true # We want to show the SQL code when the queries are executed
  main:
    web-application-type: servlet